stages:
  - build

.base_gnu:
  before_script: 
    - whoami
    - echo $PATH
    - FORTRAN_EXTRA_FLAGS="-DFORTRAN_EXTRA_FLAGS=-fimplicit-none"
    - ROOT_DIR=$CI_PROJECT_DIR
    - BUILD_DIR=$ROOT_DIR/BUILD
    - THIRDPARTY_DIR=$BUILD_DIR/THIRDPARTY
    - FEMPAR_DIR=$BUILD_DIR/FEMPAR
    - mkdir -p $THIRDPARTY_DIR
    - mkdir -p $FEMPAR_DIR
    - cd $ROOT_DIR
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - ln -sf CMake/CTestConfig_CIMNE.cmake CTestConfig.cmake


GNU_DEBUG_SERIAL:
  image: registry.gitlab.com/fempar/fempar:latest

  stage: build
  
  tags:
    - test-ci

  extends: .base_gnu
 
  script:
    - module load GNU_SERIAL
    - cd $THIRDPARTY_DIR
    - cmake -DCMAKE_BUILD_TYPE=DEBUG $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty
    - cmake --build . -- -j8
    - cd $FEMPAR_DIR
    - cmake -DPETSC_ARCH=$PETSC_ARCH -DPETSC_DIR=$PETSC_DIR -DCMAKE_BUILD_TYPE=DEBUG -DFEMPAR_ENABLE_TESTS=ON -DFEMPAR_THIRDPARTY_DIR=$THIRDPARTY_DIR -DMPIEXEC_PREFLAGS="--allow-run-as-root -oversubscribe" $ROOT_DIR
    - set +e
    - cmake --build . -- -j8
    - ctest -j8 -V -E par_test -D ExperimentalUpdate -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalCoverage -D ExperimentalMemCheck -D ExperimentalSubmit
    - serial_test_passed=0
    - test -f ./Testing/Temporary/LastTestsFailed*.log && serial_test_passed=1
    - ls -l ./Testing/Temporary/LastTestsFailed*.log
    - cat ./Testing/Temporary/LastTestsFailed*.log  
    - set -e
    - echo $serial_test_passed
    - test $serial_test_passed -eq 0

  except:
    - experimental@fempar/fempar-beta

GNU_DEBUG_PARALLEL:
  image: registry.gitlab.com/fempar/fempar:latest

  stage: build
  
  tags:
    - test-ci

  extends: .base_gnu
 
  script:
    - module load GNU_PARALLEL
    - cd $THIRDPARTY_DIR
    - cmake -DCMAKE_BUILD_TYPE=DEBUG $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty
    - cmake --build . -- -j8
    - cd $FEMPAR_DIR
    - cmake -DPETSC_ARCH=$PETSC_ARCH -DPETSC_DIR=$PETSC_DIR $FORTRAN_EXTRA_FLAGS -DCMAKE_BUILD_TYPE=DEBUG -DFEMPAR_ENABLE_TESTS=ON -DFEMPAR_THIRDPARTY_DIR=$THIRDPARTY_DIR -DMPIEXEC_PREFLAGS="--allow-run-as-root -oversubscribe" $ROOT_DIR
    - set +e
    - cmake --build . -- -j8
    - ctest -j8 -V -R par_test -D ExperimentalUpdate -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalCoverage -D ExperimentalMemCheck -D ExperimentalSubmit
    - par_test_passed=0
    - test -f ./Testing/Temporary/LastTestsFailed*.log && par_test_passed=1
    - ls -l ./Testing/Temporary/LastTestsFailed*.log
    - cat ./Testing/Temporary/LastTestsFailed*.log
    - set -e
    - echo $par_test_passed
    - test $par_test_passed -eq 0

  except:
    - experimental@fempar/fempar-beta

GNU_RELEASE_SERIAL:
  image: registry.gitlab.com/fempar/fempar:latest

  stage: build
  
  tags:
    - test-ci
 
  extends: .base_gnu

  script:
    - module load GNU_SERIAL
    - cd $THIRDPARTY_DIR
    - cmake -DCMAKE_BUILD_TYPE=DEBUG $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty
    - cmake --build . -- -j8
    - cd $FEMPAR_DIR
    - cmake -DPETSC_ARCH=$PETSC_ARCH -DPETSC_DIR=$PETSC_DIR $FORTRAN_EXTRA_FLAGS -DCMAKE_BUILD_TYPE=RELEASE -DFEMPAR_ENABLE_TESTS=ON -DFEMPAR_THIRDPARTY_DIR=$THIRDPARTY_DIR -DMPIEXEC_PREFLAGS="--allow-run-as-root -oversubscribe" $ROOT_DIR
    - set +e
    - cmake --build . -- -j8
    - ctest -j8 -V -E par_test -D ExperimentalUpdate -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalCoverage -D ExperimentalMemCheck -D ExperimentalSubmit
    - serial_test_passed=0
    - test -f ./Testing/Temporary/LastTestsFailed*.log && serial_test_passed=1
    - ls -l ./Testing/Temporary/LastTestsFailed*.log
    - cat ./Testing/Temporary/LastTestsFailed*.log  
    - set -e
    - echo $serial_test_passed
    - test $serial_test_passed -eq 0

  except:
    - experimental@fempar/fempar-beta

GNU_RELEASE_PARALLEL:
  image: registry.gitlab.com/fempar/fempar:latest

  stage: build
  
  tags:
    - test-ci
 
  extends: .base_gnu

  script:
    - module load GNU_PARALLEL
    - cd $THIRDPARTY_DIR
    - cmake -DCMAKE_BUILD_TYPE=RELEASE $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty
    - cmake --build . -- -j8
    - cd $FEMPAR_DIR
    - cmake -DPETSC_ARCH=$PETSC_ARCH -DPETSC_DIR=$PETSC_DIR $FORTRAN_EXTRA_FLAGS -DCMAKE_BUILD_TYPE=RELEASE -DFEMPAR_ENABLE_TESTS=ON -DFEMPAR_THIRDPARTY_DIR=$THIRDPARTY_DIR -DMPIEXEC_PREFLAGS="--allow-run-as-root -oversubscribe" $ROOT_DIR
    - set +e
    - cmake --build . -- -j8
    - ctest -V -R par_test -D ExperimentalUpdate -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalCoverage -D ExperimentalMemCheck -D ExperimentalSubmit
    - par_test_passed=0
    - test -f ./Testing/Temporary/LastTestsFailed*.log && par_test_passed=1
    - ls -l ./Testing/Temporary/LastTestsFailed*.log
    - cat ./Testing/Temporary/LastTestsFailed*.log
    - set -e
    - echo $par_test_passed
    - test $par_test_passed -eq 0

  except:
    - experimental@fempar/fempar-beta


.base_intel:
   before_script: 
    - FORTRAN_EXTRA_FLAGS="-DFORTRAN_EXTRA_FLAGS=-implicitnone"
    - ROOT_DIR=$CI_PROJECT_DIR
    - BUILD_DIR=$ROOT_DIR/BUILD
    - THIRDPARTY_DIR=$BUILD_DIR/THIRDPARTY
    - FEMPAR_DIR=$BUILD_DIR/FEMPAR
    - mkdir -p $THIRDPARTY_DIR
    - mkdir -p $FEMPAR_DIR
    - cd $ROOT_DIR
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - ln -sf CMake/CTestConfig_CIMNE.cmake CTestConfig.cmake

INTEL_RELEASE_SERIAL:
  image: registry.gitlab.com/fempar/fempar:latest

  stage: build
  
  tags:
    - test-ci
  
  extends: .base_intel
 
  script:
    - module load INTEL_SERIAL
    - cd $THIRDPARTY_DIR
    - cmake -DCMAKE_BUILD_TYPE=RELEASE $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty
    - cmake --build . -- -j8
    - cd $FEMPAR_DIR
    - cmake -DPETSC_ARCH=$PETSC_ARCH -DPETSC_DIR=$PETSC_DIR $FORTRAN_EXTRA_FLAGS -DCMAKE_BUILD_TYPE=RELEASE -DFEMPAR_ENABLE_TESTS=ON -DFEMPAR_THIRDPARTY_DIR=$THIRDPARTY_DIR -DMPIEXEC_PREFLAGS="--allow-run-as-root -oversubscribe" $ROOT_DIR
    - set +e
    - cmake --build . -- -j8
    - ctest -j8 -V -E par_test -D ExperimentalUpdate -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalCoverage -D ExperimentalMemCheck -D ExperimentalSubmit
    - serial_test_passed=0
    - test -f ./Testing/Temporary/LastTestsFailed*.log && serial_test_passed=1
    - ls -l ./Testing/Temporary/LastTestsFailed*.log
    - cat ./Testing/Temporary/LastTestsFailed*.log  
    - set -e
    - echo $serial_test_passed
    - test $serial_test_passed -eq 0

  except:
    - experimental@fempar/fempar-beta

INTEL_RELEASE_PARALLEL:
  image: registry.gitlab.com/fempar/fempar:latest

  stage: build
  
  tags:
    - test-ci
  
  extends: .base_intel
 
  script:
    - module load INTEL_PARALLEL
    - cd $THIRDPARTY_DIR
    - cmake -DCMAKE_BUILD_TYPE=RELEASE $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty
    - cmake --build . -- -j8
    - cd $FEMPAR_DIR
    - cmake -DPETSC_ARCH=$PETSC_ARCH -DPETSC_DIR=$PETSC_DIR $FORTRAN_EXTRA_FLAGS -DCMAKE_BUILD_TYPE=RELEASE -DFEMPAR_ENABLE_TESTS=ON -DFEMPAR_THIRDPARTY_DIR=$THIRDPARTY_DIR -DMPIEXEC_PREFLAGS="--allow-run-as-root -oversubscribe" $ROOT_DIR
    - set +e
    - cmake --build . -- -j8
    - ctest -j8 -V -R par_test -D ExperimentalUpdate -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalCoverage -D ExperimentalMemCheck -D ExperimentalSubmit
    - par_test_passed=0
    - test -f ./Testing/Temporary/LastTestsFailed*.log && par_test_passed=1
    - ls -l ./Testing/Temporary/LastTestsFailed*.log
    - cat ./Testing/Temporary/LastTestsFailed*.log
    - set -e
    - echo $par_test_passed
    - test $par_test_passed -eq 0

  except:
    - experimental@fempar/fempar-beta
