stages:
    - debug
    - release
#    - deploy

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  untracked: true
  paths:
    - $CI_PROJECT_DIR/cache

.base_gnu:
  before_script: 
    - source /opt/intel/mkl/bin/mklvars.sh intel64 
    - FORTRAN_EXTRA_FLAGS="-DFORTRAN_EXTRA_FLAGS=-fimplicit-none"
    - ROOT_DIR=$CI_PROJECT_DIR
    - BUILD_DIR=/data/BUILD
    - FEMPAR_DIR=$BUILD_DIR/FEMPAR
    - mkdir -p $FEMPAR_DIR
    - cd $ROOT_DIR
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - ln -sf CMake/CTestConfig_CIMNE.cmake CTestConfig.cmake


GNU_DEBUG_P4EST_SERIAL:
  image: fempar/fempar-env:gnu-debug_p4est-serial
  stage: debug
  tags:
    - test-ci
  only:
    - experimental@fempar/fempar
  extends: .base_gnu
  script:
    - THIRDPARTY_DIR=$CI_PROJECT_DIR/cache/gnu/debug/THIRDPARTY
    - mkdir -p $THIRDPARTY_DIR
    - cd $THIRDPARTY_DIR
    - cmake -DCMAKE_BUILD_TYPE=DEBUG $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty
    - cmake --build . -- -j8
    - cd $FEMPAR_DIR
    - cmake -DPETSC_ARCH=$PETSC_ARCH -DPETSC_DIR=$PETSC_DIR -DCMAKE_BUILD_TYPE=DEBUG -DFEMPAR_ENABLE_TESTS=ON -DFEMPAR_THIRDPARTY_DIR=$THIRDPARTY_DIR -DMPIEXEC_PREFLAGS="--allow-run-as-root -oversubscribe" $ROOT_DIR
    - set +e
    - cmake --build . -- -j8
    - ctest -j8 -V -L SERIAL -D ExperimentalUpdate -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit
    - serial_test_passed=0
    - test -f ./Testing/Temporary/LastTestsFailed*.log && serial_test_passed=1
    - ls -l ./Testing/Temporary/LastTestsFailed*.log
    - cat ./Testing/Temporary/LastTestsFailed*.log  
    - set -e
    - echo $serial_test_passed
    - test $serial_test_passed -eq 0


GNU_DEBUG_P4EST_SERIAL_FAST:
  image: fempar/fempar-env:gnu-debug_p4est-serial
  stage: debug
  tags:
    - test-ci
  except:
    - experimental
  extends: .base_gnu
  script:
    - THIRDPARTY_DIR=$CI_PROJECT_DIR/cache/gnu/debug/THIRDPARTY
    - mkdir -p $THIRDPARTY_DIR
    - cd $THIRDPARTY_DIR
    - cmake -DCMAKE_BUILD_TYPE=DEBUG $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty
    - cmake --build . -- -j8
    - cd $FEMPAR_DIR
    - cmake -DPETSC_ARCH=$PETSC_ARCH -DPETSC_DIR=$PETSC_DIR -DCMAKE_BUILD_TYPE=DEBUG -DFEMPAR_ENABLE_TESTS=ON -DFEMPAR_THIRDPARTY_DIR=$THIRDPARTY_DIR -DMPIEXEC_PREFLAGS="--allow-run-as-root -oversubscribe" $ROOT_DIR
    - set +e
    - cmake --build . -- -j8
    - ctest -j8 -V -L SERIAL_FAST -D ExperimentalUpdate -D ExperimentalStart -D ExperimentalConfigure -D ExperimentalBuild -D ExperimentalTest -D ExperimentalSubmit
    - serial_test_passed=0
    - test -f ./Testing/Temporary/LastTestsFailed*.log && serial_test_passed=1
    - ls -l ./Testing/Temporary/LastTestsFailed*.log
    - cat ./Testing/Temporary/LastTestsFailed*.log  
    - set -e
    - echo $serial_test_passed
    - test $serial_test_passed -eq 0


GNU_DEBUG_P4EST_PARALLEL:
  image: fempar/fempar-env:gnu-debug_p4est-parallel
  stage: debug
  tags:
    - test-ci
  except:
    - experimental@fempar/fempar-beta
  extends: .base_gnu
  script:
    - THIRDPARTY_DIR=$CI_PROJECT_DIR/cache/gnu/debug/THIRDPARTY
    - mkdir -p $THIRDPARTY_DIR
    - cd $THIRDPARTY_DIR
    - cmake -DCMAKE_BUILD_TYPE=DEBUG $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty
    - cmake --build . -- -j8


GNU_RELEASE_P4EST_SERIAL:
  image: fempar/fempar-env:gnu-release_p4est-serial
  stage: release
  tags:
    - test-ci
  except:
    - experimental@fempar/fempar-beta
  extends: .base_gnu
  script:
    - THIRDPARTY_DIR=$CI_PROJECT_DIR/cache/gnu/release/THIRDPARTY
    - mkdir -p $THIRDPARTY_DIR
    - cd $THIRDPARTY_DIR
    - cmake -DCMAKE_BUILD_TYPE=RELEASE $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty
    - cmake --build . -- -j8


GNU_RELEASE_P4EST_PARALLEL:
  image: fempar/fempar-env:gnu-release_p4est-parallel
  stage: release
  tags:
    - test-ci
  except:
    - experimental@fempar/fempar-beta
  extends: .base_gnu
  script:
    - THIRDPARTY_DIR=$CI_PROJECT_DIR/cache/gnu/release/THIRDPARTY
    - mkdir -p $THIRDPARTY_DIR
    - cd $THIRDPARTY_DIR
    - cmake -DCMAKE_BUILD_TYPE=RELEASE $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty
    - cmake --build . -- -j8


.base_intel:
   before_script: 
    - source /usr/local/Modules/init/bash 
    - FORTRAN_EXTRA_FLAGS="-DFORTRAN_EXTRA_FLAGS=-implicitnone"
    - ROOT_DIR=$CI_PROJECT_DIR
    - BUILD_DIR=$ROOT_DIR/BUILD
    - FEMPAR_DIR=$BUILD_DIR/FEMPAR
    - mkdir -p $FEMPAR_DIR
    - cd $ROOT_DIR
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - ln -sf CMake/CTestConfig_CIMNE.cmake CTestConfig.cmake


INTEL_RELEASE_P4EST_SERIAL:
  image: registry.gitlab.com/fempar/fempar-beta:latest
  stage: release
  tags:
    - test-ci
  except:
    - experimental@fempar/fempar-beta
  extends: .base_intel
  script:
    - module load INTEL_SERIAL
    - THIRDPARTY_DIR=$CI_PROJECT_DIR/cache/intel/release/THIRDPARTY
    - mkdir -p $THIRDPARTY_DIR
    - cd $THIRDPARTY_DIR
    - cmake -DCMAKE_BUILD_TYPE=RELEASE $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty
    - cmake --build . -- -j8


INTEL_RELEASE_P4EST_PARALLEL:
  image: registry.gitlab.com/fempar/fempar-beta:latest
  stage: release
  tags:
    - test-ci
  except:
    - experimental@fempar/fempar-beta
  extends: .base_intel
  script:
    - module load INTEL_PARALLEL
    - THIRDPARTY_DIR=$CI_PROJECT_DIR/cache/intel/release/THIRDPARTY
    - mkdir -p $THIRDPARTY_DIR
    - cd $THIRDPARTY_DIR
    - cmake -DCMAKE_BUILD_TYPE=RELEASE $FORTRAN_EXTRA_FLAGS $ROOT_DIR/ThirdParty
    - cmake --build . -- -j8
